version: '3'

services:
  prometheus_server:
    image: prom/prometheus:v2.45.0
    container_name: prometheus_server
    ports:
      - "9091:9090"
    volumes:
      - "./prom_config/prometheus.yaml:/etc/prometheus/prometheus.yaml"

  grafana_ui:
    image: grafana/grafana:9.5.6
    container_name: grafana_ui
    ports:
      - "3001:3000"
