version: "3"

services:
  prometheus_server:
    image: prom/prometheus:v2.45.0
    container_name: prometheus_server
    restart: always
    ports:
      - "9091:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - prometheus_data:/prometheus
      # - "~/.docker-volumes/prometheus:/prometheus"

  grafana_ui:
    image: grafana/grafana:9.5.6
    container_name: grafana_ui
    ports:
      - "3001:3000"
    volumes:
      # - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana-storage:/var/lib/grafana
      # - "~/.docker-volumes/grafana:/var/lib/grafana"

  golang_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: prom-graf:latest
    container_name: prom_graf_app
    restart: always
    ports:
      - "2021:2020"

volumes:
  prometheus_data:
  grafana-storage:
