version: '3'

services:
  prometheus_server:
    image: prom/prometheus:v2.45.0
    container_name: prometheus_server
    ports:
      - "9091:9090"
    volumes:
      - "./prometheus_config/prometheus.yaml:/etc/prometheus/prometheus.yaml"
      - "~/.docker-volumes/prometheus:/prometheus"

  grafana_ui:
    image: grafana/grafana:9.5.6
    container_name: grafana_ui
    ports:
      - "3001:3000"
    volumes:
      - "~/.docker-volumes/grafana:/var/lib/grafana"

  golang_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: prom-graf:latest
    container_name: prom_graf_app
    ports:
      - "2021:2020"
